### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by MoonCheung** [CQBoyBrand/Koa2-nuxt-MySQL#1]
我已经将您的源代码克隆下载，然后将后台输入`npm run serve`，server输入`npm run dev`，都可运行来打开查看网页显示账号以及密码多少？想体验下

**Comment by CQBoyBrand** [comment]
> 我已经将您的源代码克隆下载，然后将后台输入`npm run serve`，server输入`npm run dev`，都可运行来打开查看网页显示账号以及密码多少？想体验下

这个需要自己本地搭建数据库哦。。暂时没有提供体验的站点

**Comment by MoonCheung** [comment]
好吧，根据你发布源代码值得提供参考呢
