### ISSUE TITLE
登录失败问题

### ISSUE THREAD

**Issue by MoonCheung** [CQBoyBrand/Koa2-nuxt-MySQL#2]
从您的源代码下载最新了，里有blog.sql导入本地数据库成功然后手动添加用户信息分别`insert into user(username，password，nickname) values(*，*，*)`，还有这个password从浏览器登录页输入密码生成密码含有MD5复制下放入本地数据库，然后再次向浏览器登录页登录尝试下结果出现提示框登录失败。什么原因呢，有什么地方还没解决呢

**Comment by CQBoyBrand** [comment]
> 从您的源代码下载最新了，里有blog.sql导入本地数据库成功然后手动添加用户信息分别`insert into user(username，password，nickname) values(*，*，*)`，还有这个password从浏览器登录页输入密码生成密码含有MD5复制下放入本地数据库，然后再次向浏览器登录页登录尝试下结果出现提示框登录失败。什么原因呢，有什么地方还没解决呢

应该是密码错了，前端和服务端都做了MD5加密，你直接这样在数据库添加用户是不行的，有个register方法，你先把登录页面的this.Ajax.login方法换成this.Ajax.register方法注册一个用户在登录应该就好了

**Comment by MoonCheung** [comment]
![image](https://user-images.githubusercontent.com/19801190/57567186-f8d7dc00-7407-11e9-85a5-b6f996d1f37c.png)
![image](https://user-images.githubusercontent.com/19801190/57567200-350b3c80-7408-11e9-813f-cd9c5dc9117f.png)
![image](https://user-images.githubusercontent.com/19801190/57567259-0d68a400-7409-11e9-95e0-549c6ab1a3a9.png)
已经将`this.Ajax.login`方法更改成`this.Ajax.register`方法注册还是失败呢

**Comment by CQBoyBrand** [comment]
> ![image](https://user-images.githubusercontent.com/19801190/57567186-f8d7dc00-7407-11e9-85a5-b6f996d1f37c.png)
> ![image](https://user-images.githubusercontent.com/19801190/57567200-350b3c80-7408-11e9-813f-cd9c5dc9117f.png)
> ![image](https://user-images.githubusercontent.com/19801190/57567259-0d68a400-7409-11e9-95e0-549c6ab1a3a9.png)
> 已经将`this.Ajax.login`方法更改成`this.Ajax.register`方法注册还是失败呢

你看是不是config.AUTH.pwdSalt报错了

**Comment by MoonCheung** [comment]
没看出来报错，是没有反应呢，还有另外我本地mysql数据库出现问题`mysql>mysql -uroot -proot;`出现报错，`mysql>mysql -uroot;`可运行来呢

**Comment by CQBoyBrand** [comment]
> 没看出来报错，是没有反应呢，还有另外我本地mysql数据库出现问题`mysql>mysql -uroot -proot;`出现报错，`mysql>mysql -uroot;`可运行来呢

数据库问题不清楚，我边代码是可以成功的，你在看看书不是数据库的问题吧

**Comment by MoonCheung** [comment]
是数据库问题，您的源代码需要本地数据库用户root和密码root可跑起来，我已经解决了，另外从server文件夹里面index.js里面配置session中间件一些代码报错呢
![image](https://user-images.githubusercontent.com/19801190/57567786-178ea080-7411-11e9-9f73-30afc2d30226.png)

**Comment by MoonCheung** [comment]
忘了说声谢谢你，将登录问题解决了呢

**Comment by CQBoyBrand** [comment]
> 是数据库问题，您的源代码需要本地数据库用户root和密码root可跑起来，我已经解决了，另外从server文件夹里面index.js里面配置session中间件一些代码报错呢
> ![image](https://user-images.githubusercontent.com/19801190/57567786-178ea080-7411-11e9-9f73-30afc2d30226.png)

这个目前没有用到这个，可以注释掉

**Comment by MoonCheung** [comment]
好的👌
