### ISSUE TITLE
跑不起来，server显示token过期，请重新登录

### ISSUE THREAD

**Issue by tomixiaohei** [CQBoyBrand/Koa2-nuxt-MySQL#3]

**Comment by CQBoyBrand** [comment]
看下这个issue有没有解决你的问题，他跑起来了，我试下了也是能跑起来的～
[https://github.com/CQBoyBrand/Koa2-nuxt-MySQL/issues/2](https://github.com/CQBoyBrand/Koa2-nuxt-MySQL/issues/2)

另外：token是登陆成功后6小时过期，需要重新登陆～～

**Comment by tomixiaohei** [comment]
不行呢  他的步骤我都试过了呢

**Comment by CQBoyBrand** [comment]
> 不行呢 他的步骤我都试过了呢

emmmmmmm..那就不太清楚了。。。。我重新吧代码拉下来跑了下，也是可以的

**Comment by CQBoyBrand** [comment]
我应该知道你什么情况了，你应该访问的是localhost://3500出现的token过期吧。。。这个端口是只用来提供接口的。并不是运行amdin的，要启动admin，请进入admin文件夹执行npm run serve

**Comment by tomixiaohei** [comment]
确实... admin那个点了无反应，话说默认账号密码多少？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "重庆崽儿Brand"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午4:28
收件人: "CQBoyBrand/Koa2-nuxt-MySQL"<Koa2-nuxt-MySQL@noreply.github.com&gt;; 
抄送: "絕對ヤ帥気"<505004141@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CQBoyBrand/Koa2-nuxt-MySQL] 跑不起来，server显示token过期，请重新登录 (#3)




我应该知道你什么情况了，你应该访问的是localhost://3500出现的token过期吧。。。这个端口是只用来提供接口的。并不是运行amdin的，要启动admin，请进入admin文件夹执行npm run serve

**Comment by tomixiaohei** [comment]
按照他的步骤试过注册，但是显示注册失败呢
